### ISSUE TITLE
Demo-Tryout-Errors

### ISSUE THREAD

**Issue by CeeYaa** [vvvv/VL.Devices.Astra#1]
VL.Devices.Astra/vvvv/girlpower/AstraDemo.v4p - not working in alphaVVVV(180701) redNode
VL.Devices.Astra-master\help\Orbbec\Astra\Demo.vl - works in gamma411 but SkiaColorFilter Brightness is not existing had to add ColorFilterLighness to see something

**Comment by joreg** [comment]
beta demo is now fixed.
gamma demo also works with latest gamma.
